DROP DATABASE IF EXISTS DBREVENDAVEICULOS;
CREATE DATABASE  DBREVENDAVEICULOS;

USE DBREVENDAVEICULOS;

CREATE TABLE CLIENTE (
IDCLIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT
, NOME VARCHAR(255)
, CPF CHAR(11)
, TELEFONE VARCHAR(255)
);

CREATE TABLE VEICULO (
IDVEICULO INT NOT NULL PRIMARY KEY AUTO_INCREMENT
, MODELO VARCHAR(255)
, TIPO ENUM('CARRO','MOTO','SUV')
, FABRICANTE VARCHAR(255)
, ANO INTEGER(4)
, COR VARCHAR(255)
, PLACA VARCHAR(255)
);

CREATE TABLE VENDA (
IDVENDA INT NOT NULL PRIMARY KEY AUTO_INCREMENT
, IDCLIENTE INT, FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE (IDCLIENTE)
, IDVEICULO INT, FOREIGN KEY (IDVEICULO) REFERENCES VEICULO (IDVEICULO)
, VALORVENDA DECIMAL(10,2)
, DATAVENDA DATE
);